# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2187cf433639f04ebb7fc353702031d0a7f038a31024b4828b50a496b87d5a6d74fcb2b31bb43f48b3fe1750e94aa39391fc1fa7334b2c0a60af8c1b799ea7a4

test:
  secret_key_base: 092c7b8904ea3c5d6b2868456e4150d93e2c2b5e3a1d01f6afda3151af522125d01062299aba31868b96e2eef00871ff9f021bdd55162ce06a8fa503a4409f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
